server:
  url: http://localhost
  port: 8080
  allow_origins:
    - "https://admin.hakka.rice9547.org"
    - "http://localhost:3000"

database:
  host:
  port:
  username:
  password:
  name:

auth0:
  domain:
  audience:

upload:
  endpoint:
  image_bucket:
  audio_bucket:
  region:
  access_key:
  secret_key:

openai:
  api_key:
