server:
  url:
  port:

database:
  host:
  port:
  username:
  password:
  name:

auth0:
  domain:
  audience:

upload:
  endpoint:
  image_bucket:
  audio_bucket:
  region:
  access_key:
  secret_key:

openai:
  api_key:
